<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-a00377571/blob/main/Modulo5_IBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('assignment01 for GitJobish03 and edited in git, and 18')

assignment01 for GitJobish03 and edited in git, and 18


MARCO ANTONIO ARELLANO HERNÁNDEZ.
A00377571 





##            **Arreglos Numpy y API's**









**MODULO 5**


# **Laboratorio de Arreglos Numpy de una dimensión.**

Objetivos:
Importar y usar la libreria "numpy" y hacer operaciones con numpy de 1D una dimensión.


In [4]:
#Crear una lista de python.
a=["0",1,"two","3",4] 
#podemos accesar a los elementos con los indices y corchetes.
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

#

0
1
two
3
4


¿Qué es un numpy?
Es una librería usada para trabajar con arreglos, algebra linear, transformada de furier y matrices. Un arreglo numpy, es similar a una lista, pero con soporte para python numérico y es un de código abierto. El objeto arreglo en Numpy es llamada "nDarray" y provee un gran cantidad de funciones de soporte para trabajar con arreglos "ndarray" muy facil.

Los arreglos son frecuentemente usados en ciencia de datos, donde la velocidad y recursos son muy importantes.

Normalmente la libreria numpy es importada con el alias "np".



In [5]:
#Importanto la librería numpy.
import numpy as np


In [7]:
# entonces enviamos a un arreglo numpy la lista "a".

a= np.array([0,1,2,3])
print(a) #todos los arreglos numpy deben tener el mismo tipo de elementos.


[0 1 2 3]


In [9]:
#así como la lista todos los elementos pueden ser
#accesados por el indice en el corchete.
a[3]

3

In [10]:
# el arreglo es guardado bajo una versión de atributo.
print(np.__version__) # esta versión servirá para 

1.21.6


In [12]:
#TYPE. obtener el tipo de archivo en el nparray
type(a)

numpy.ndarray

In [13]:
#para obtener el tipo de los valores guardados en el archivo.
a.dtype # se observa que son enteros.

dtype('int64')

In [14]:
#para la siguiente lista obtener el tipo de arreglo y tipo de datos guardados en el arreglo.
b=np.array([3.1,11.02,6.2,213.2,5.2])


In [15]:
type(b)

numpy.ndarray

In [16]:
b.dtype

dtype('float64')

Asignar un valor al arreglo numpy.

In [17]:
# arreglo numpy
c=([20,1,2,3,4])

In [18]:
c


[20, 1, 2, 3, 4]

In [19]:
# cambia el valor de 20 a 100
c[0]=100

In [20]:
c

[100, 1, 2, 3, 4]

# **Slicing;** significa tomar los elementos de un índice dado y asignarlos a otro numpy array en otro indice.


In [21]:
c

[100, 1, 2, 3, 4]

In [22]:
d=c[1:4]

In [23]:
d

[1, 2, 3]

In [25]:
#fija el valor del 4to y 5to elemento en 300 y 400.
c[3:5]=300,400
c

[100, 1, 2, 300, 400]

In [26]:
# STEPS Slicing, podemos definir pasos a cortar [start:end:step]
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [31]:
#si no escribe inicio se considera 0.
arr[:4]


array([1, 2, 3, 4])

In [32]:
#si no escribes final se considera todos los demas.
arr[4:]


array([5, 6, 7])

In [33]:
#si no se da paso se considera 1.
arr[1:5:]

array([2, 3, 4, 5])